### ISSUE TITLE
Fiftyone Unable to Update View

### ISSUE THREAD

**Issue by Xu-Justin** [danilhendrasr/semi-automated-labeling#48]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/local/apps/dash/app_flask.py", line 43, in fiftyone_load
    session.view = view
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/session/session.py", line 211, in wrapper
    result = func(session, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/session/session.py", line 554, in view
    view._root_dataset._reload()
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/dataset.py", line 4597, in _reload
    self._doc.reload()
  File "/usr/local/lib/python3.9/site-packages/mongoengine/document.py", line 746, in reload
    raise self.DoesNotExist("Document does not exist")
fiftyone.core.odm.dataset.DoesNotExist: Document does not exist
Exception on /fiftyone/update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/local/apps/dash/app_flask.py", line 43, in fiftyone_load
    session.view = view
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/session/session.py", line 211, in wrapper
    result = func(session, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/session/session.py", line 554, in view
    view._root_dataset._reload()
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/dataset.py", line 4597, in _reload
    self._doc.reload()
  File "/usr/local/lib/python3.9/site-packages/mongoengine/document.py", line 746, in reload
    raise self.DoesNotExist("Document does not exist")
fiftyone.core.odm.dataset.DoesNotExist: Document does not exist
```

**Comment by Xu-Justin** [comment]
```
raise mongoengine.NotUniqueError(message % err)
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: fiftyone.datasets index: name_1 dup key: { name: null }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'name': 1}, 'keyValue': {'name': None}, 'errmsg': 'E11000 duplicate key error collection: fiftyone.datasets index: name_1 dup key: { name: null }'})
```

**Comment by Xu-Justin** [comment]
Problem related to #40
